name: "Publish To Github"
description: "Push/Update Branch from a directory. Built for compilaiton to creating actions, publishing Github Pages"
inputs:
  repo_name:
    description: "Repository name with owner. For example, cedric05/dothttp"
    required: true
    default: ${{ github.repository }}
  branch:
    description: The branch to push
    required: true
  directory:
    description: "Directory to push"
    required: true
  commit_message:
    description: "commit message"
    required: true
    default: "publish directory to branch"
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: rodrigorodriguescosta/checkout@main
      with:
        repository: ${{ inputs.repo_name }}
        path: /tmp/${{ inputs.repo_name }}
        ref: ${{ inputs.branch }}
    - run: |
        cd /tmp/${{ inputs.repo_name }}
        rm -rf *
        cp -r ${{ inputs.directory }}/. /tmp/${{ inputs.repo_name }}
        git config --global user.email "actions@github.com"
        git config --global user.name "gh-actions"
        git add -A
        git commit -m "${{ inputs.commit_message }}"
        git push origin ${{ inputs.branch }}
        rm -rf . # do we have to clean up??
      shell: bash
